services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    command: sh -c "npm install && npm run dev"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]

volumes:
  node_modules_cache:
