services:
  db_handler:
    build:
      context: .
      dockerfile: ./db/.docker/ci/Dockerfile
    ports:
      - "8003:${DB_HANDLER_PORT}"
  execution_engine:
    build:
      context: .
      dockerfile: ./execution_engine/.docker/ci/Dockerfile
      args:
        HOST_DOCKER_GID: ${HOST_DOCKER_GID}
    ports:
      - "8002:${EXECUTION_ENGINE_PORT}"
  server_interface:
    build:
      context: .
      dockerfile: ./server/.docker/ci/Dockerfile
    ports:
      - "8001:${SERVER_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    command: sh -c "npm install && npm run dev"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]

volumes:
  node_modules_cache:
