services:
  db_handler:
    build:
      context: .
      dockerfile: ./db/.docker/ci/Dockerfile
      args:
        # If anyone finds a way to parse UID/GID on Github Workflows let me know
        - UID=1000
        - GID=1000

  execution_engine:
    build:
      context: .
      dockerfile: ./execution_engine/.docker/ci/Dockerfile

  server_interface:
    build:
      context: .
      dockerfile: ./server/.docker/ci/Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/ci/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]

volumes:
  storage:
