services:
  db_handler:
    build:
      context: .
      dockerfile: ./db/.docker/ci/Dockerfile

  execution_engine:
    build:
      context: .
      dockerfile: ./execution_engine/.docker/ci/Dockerfile
      args:
        HOST_DOCKER_GID: ${HOST_DOCKER_GID}
        HOST_USER_UID: ${HOST_USER_UID}

  server_interface:
    build:
      context: .
      dockerfile: ./server/.docker/ci/Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/ci/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
