services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ci
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
