services:
  server:
    container_name: server_interface
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend_private:
    external: true
  backend_public:
    external: true