services:
  db_handler:
    container_name: db_handler
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend_private:
    external: true
