FROM postgres:latest

# Set environment variables for Postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres    

# Copy initialization scripts if we have any
# COPY initdb.d /docker-entrypoint-initdb.d/

