# This file is part of the Docker compose configuration for a PostgreSQL database.
services:
  postgres_db:
    build: .
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env